### ISSUE TITLE
no error message for missing isotropic source files

### ISSUE THREAD

**Issue by jefemagril** [fermiPy/fermipy#158] opened 2017-10-11 20:05 UTC
If you define different isotropic source files for different components and the files are not found, there is no error message. Instead, it simply does not include an isodiff source in the model.

**Comment by jefemagril** [comment] 2017-10-11 20:12
There seems to be a recent changes that is causing no isotropic source to be made during `setup()`, even with the necessary files there. I don't have time to look into the cause, but the problem was fixed when I went back to tag 0.15.1.

**Comment by woodmd** [comment] 2017-10-12 13:58
I think I know what the issue is.  I'll plan to have a look at this next week but in the meantime you should be able to fix it by defining an isotropic component in the root configuration.

**Comment by woodmd** [comment] 2017-10-16 19:35
Should now be fixed with #159.  Please give this a try and let me know if you're still encountering this issue.

**Comment by jefemagril** [comment] 2017-11-01 17:54
Thanks @woodmd, it appears to be fixed now.

**Comment by jefemagril** [comment] 2017-11-01 17:57
Sorry I just realized there was a test I hadn't done yet.

**Closed** 2017-11-01 17:56 UTC

**Comment by jefemagril** [comment] 2017-11-01 18:02
Ok, yes it looks good.
