### ISSUE TITLE
cfitsio error running GTBinnedAnalysis (srcmaps)

### ISSUE THREAD

**Issue by sonnenblu** [fermiPy/fermipy#253] opened 2018-10-18 14:58 UTC
I am running Fermipy on Ubuntu 16.04 with all setups as recommended (initializing heasoft, Fermi science tools, conda setup). I am constantly getting a cfitsio error and can't figure out what the issue is. I am using the new F8YL catalog and the same problem exists even with the 3FGL catalog. Any help is highly appreciated. I have copied the error msg below.

----------
018-10-18 09:41:46 INFO    GTBinnedAnalysis.run_gtapp(): Caught N3tip12TipExceptionE at the top level: Could not open FITS extension "/home/data/fermi/results/srcmap_03.fits[1547]" (CFITSIO ERROR 107: tried to move past end of file)
2018-10-18 09:41:46 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtsrcmaps. Execution time: 215.81 s
2018-10-18 09:41:46 INFO    GTBinnedAnalysis.setup(): Finished setup for component 03
2018-10-18 09:41:46 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 00.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-1e27b2b06e27> in <module>()
----> 1 gta.setup()

/home/anaconda2/lib/python2.7/site-packages/fermipy/gtanalysis.pyc in setup(self, init_sources, overwrite, **kwargs)
   1040 
   1041         # Create likelihood
-> 1042         self._create_likelihood()
   1043 
   1044         # Determine tmin, tmax

/home/anaconda2/lib/python2.7/site-packages/fermipy/gtanalysis.pyc in _create_likelihood(self, srcmdl)
   1065         self._like = SummedLikelihood()
   1066         for c in self.components:
-> 1067             c._create_binned_analysis(srcmdl)
   1068             self._like.addComponent(c.like)
   1069 

/home/anaconda2/lib/python2.7/site-packages/fermipy/gtanalysis.pyc in _create_binned_analysis(self, xmlfile, **kwargs)
   5278         self.logger.debug(kw)
   5279 
-> 5280         self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
   5281 
   5282         # Create BinnedAnalysis

/home/software/ScienceToolsFermiv11r5p3/x86_64-unknown-linux-gnu-libc2.23/lib/python/BinnedAnalysis.pyc in __init__(self, srcMaps, expCube, binnedExpMap, irfs, phased_expmap)
     62         # EAC switch to using AppHelpers...
     63         self.countsMap = pyLike.AppHelpers_readCountsMap(srcMaps)
---> 64         self._createObservation(srcMaps, expCube, self.irfs)
     65     def _createObservation(self, srcMaps, expCube, irfs):
     66         self._respFuncs = pyLike.ResponseFunctions()

/home/software/ScienceToolsFermiv11r5p3/x86_64-unknown-linux-gnu-libc2.23/lib/python/BinnedAnalysis.pyc in _createObservation(self, srcMaps, expCube, irfs)
     65     def _createObservation(self, srcMaps, expCube, irfs):
     66         self._respFuncs = pyLike.ResponseFunctions()
---> 67         self._respFuncs.load_with_event_types(irfs, "", self.srcMaps, "")
     68         self._expMap = pyLike.ExposureMap()
     69         self._scData = pyLike.ScData()

/home/software/ScienceToolsFermiv11r5p3/x86_64-unknown-linux-gnu-libc2.23/lib/python/pyLikelihood.pyc in load_with_event_types(*args)
   6666             string extname)
   6667         """
-> 6668         return lib_pyLikelihood.ResponseFunctions_load_with_event_types(*args)
   6669 
   6670 ResponseFunctions_swigregister = lib_pyLikelihood.ResponseFunctions_swigregister

RuntimeError: Cannot read keyword "NDSKEYS" in file "/home/data/fermi/results/srcmap_00.fits" (CFITSIO ERROR 202: keyword not found in header)

--------------------

Thanks for any help/suggestions to resolve this!

**Comment by sonnenblu** [comment] 2018-10-25 16:18
Is someone able to help me with this issue? I would like to continue with my analysis, but can't move ahead without figuring out what's causing this issue.. thanks.

**Comment by sonnenblu** [comment] 2018-10-25 17:03
Yes, the first error actually starts from "Could not open FITS extension "/home/data/fermi/results/srcmap_00.fits[1547]" (CFITSIO ERROR 107: tried to move past end of file)"

Then goes on with the analysis running the setup for component 01 until it gets to srcmap and gives the same error for srcmap_01.fits etc. The script does generate different sourcemap as I can see the list being created. After the galdff and isodiff, the error comes up as "Caught N3tipExceptionE at the top level: could not open....."

**Comment by sonnenblu** [comment] 2018-10-25 17:53
Here's the full output (less all the sourcemaps generated..).

All initial setup as such:

%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
from fermipy.gtanalysis import GTAnalysis
gta = GTAnalysis('1547config.yaml',logging={'verbosity' : 3})

Running the gta.setup() next:

2018-10-25 12:18:13 INFO    GTAnalysis.setup(): Running setup.
2018-10-25 12:18:13 INFO    GTBinnedAnalysis.setup(): Running setup for component 00
2018-10-25 12:18:13 INFO    GTBinnedAnalysis._select_data(): Skipping data selection.
2018-10-25 12:18:13 INFO    GTBinnedAnalysis._create_ltcube(): Skipping LT Cube.
2018-10-25 12:18:13 INFO    GTBinnedAnalysis._create_expcube(): Skipping gtexpcube.
2018-10-25 12:18:14 INFO    GTBinnedAnalysis.run_gtapp(): Running gtsrcmaps.
2018-10-25 12:18:14 INFO    GTBinnedAnalysis.run_gtapp(): time -p /home/software/ScienceToolsFermiv11r5p3/x86_64-unknown-linux-gnu-libc2.23/bin/gtsrcmaps scfile=/home/data/fermi/1547sc.fits sctable="SC_DATA" expcube=/home/data/fermi/results/ltcube_00.fits cmap=/home/data/fermi/results/ccube_00.fits srcmdl=/home/data/fermi/results/srcmdl_00.xml bexpmap=/home/data/fermi/results/bexpmap_00.fits wmap=none outfile=/home/data/fermi/results/srcmap_00.fits irfs="P8R2_SOURCE_V6" evtype=4 convol=yes resample=yes rfactor=2 minbinsz=0.05 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=3 clobber=yes debug=no gui=no mode="ql"
2018-10-25 12:19:45 INFO    GTBinnedAnalysis.run_gtapp(): This is gtsrcmaps version HEAD
2018-10-25 12:19:45 INFO    GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R2_SOURCE_V6 (PSF)
2018-10-25 12:19:45 INFO    GTBinnedAnalysis.run_gtapp(): event_types:  2
2018-10-25 12:19:45 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named FL8Y J1548.6-5345
2018-10-25 12:19:45 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named FL8Y J1545.5-5416
......... Goes on to create the list of sources
.........
2018-10-25 12:22:49 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for FL8Y J1647.6-5828....................!
2018-10-25 12:22:49 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for galdiff....................!
2018-10-25 12:22:49 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for isodiff....................!
2018-10-25 12:22:49 INFO    GTBinnedAnalysis.run_gtapp(): Caught N3tip12TipExceptionE at the top level: Could not open FITS extension "/home/data/fermi/results/srcmap_00.fits[1547]" (CFITSIO ERROR 107: tried to move past end of file)
2018-10-25 12:22:49 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtsrcmaps. Execution time: 275.34 s
2018-10-25 12:22:49 INFO    GTBinnedAnalysis.setup(): Finished setup for component 00
2018-10-25 12:22:49 INFO    GTBinnedAnalysis.setup(): Running setup for component 01
2018-10-25 12:22:49 INFO    GTBinnedAnalysis._select_data(): Skipping data selection.
2018-10-25 12:22:49 INFO    GTBinnedAnalysis._create_ltcube(): Skipping LT Cube.
2018-10-25 12:22:49 INFO    GTBinnedAnalysis._create_expcube(): Skipping gtexpcube.
2018-10-25 12:22:49 INFO    GTBinnedAnalysis.run_gtapp(): Running gtsrcmaps.
2018-10-25 12:22:49 INFO    GTBinnedAnalysis.run_gtapp(): time -p /home/software/ScienceToolsFermiv11r5p3/x86_64-unknown-linux-gnu-libc2.23/bin/gtsrcmaps 
......
......
2018-10-25 12:24:36 INFO    GTBinnedAnalysis.run_gtapp(): This is gtsrcmaps version HEAD
2018-10-25 12:24:36 INFO    GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R2_SOURCE_V6 (PSF)
2018-10-25 12:24:36 INFO    GTBinnedAnalysis.run_gtapp(): event_types:  3
2018-10-25 12:24:36 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named FL8Y J1548.6-5345
2018-10-25 12:24:36 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named FL8Y J1545.5-5416
..........
..........
2018-10-25 12:26:54 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for galdiff....................!
2018-10-25 12:26:54 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for isodiff....................!
2018-10-25 12:26:54 INFO    GTBinnedAnalysis.run_gtapp(): Caught N3tip12TipExceptionE at the top level: Could not open FITS extension "/home/data/fermi/results/srcmap_01.fits[1547]" (CFITSIO ERROR 107: tried to move past end of file)
2018-10-25 12:26:54 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtsrcmaps. Execution time: 244.40 s
2018-10-25 12:26:54 INFO    GTBinnedAnalysis.setup(): Finished setup for component 01
2018-10-25 12:26:54 INFO    GTBinnedAnalysis.setup(): Running setup for component 02
.......
.....

Goes on to do component 03 and eventually ends up with the final error that was copied in the first msg.
​

**Comment by dimauromattia** [comment] 2018-10-29 16:50
Hi @sonnenblu . When I have encountered a similar error there was an other message error before "Caught N3tip12TipExceptionE at the top level: Could not open FITS extension "/home/data/fermi/results/srcmap_01.fits[1547]" (CFITSIO ERROR 107: tried to move past end of file)". I would need more informations to help you. Could you share the files you have in the analysis (ft1, ft2, ltcube, scrmao, config.yaml,...)? Also I suggest to delete all the files generated by gta.setup() and try to re-run it and see if you still have that error.

**Comment by sonnenblu** [comment] 2018-10-30 12:12
Thank you for responding and I really appreciate all the help! Ok, I deleted all the files and ran the analysis again. I still get the error and some warning messages before the CFITSIO error. I have copied the contents from the *yaml file and the error msg here. I am not sure how to share the ft1, ft2, ltcube files etc. as when I try to attach them, I get the msg that fits files are not supported.

Contents of yaml file:
-----------
data:
  evfile : /home/data/1547/fermi/1547events.txt
  scfile : /home/data/1547/fermi/1547sc.fits
  ltcube : null

binning:
  roiwidth   : 10.0
  binsz      : 0.1
  binsperdec : 8

selection :
  emin : 100
  emax : 300000
  zmax : 100
  evclass : 128
  evtype : 3
  tmin : 239557417
  tmax : 562510675
  filter : null
  target : 'FL8Y J1551.0-5422'

gtlike:
  edisp : True
  irfs  : 'P8R2_SOURCE_V6'
  edisp_disable : ['isodiff','galdiff']

model:
  src_roiwidth : 15.0
  galdiff  : 'gll_iem_v06.fits'
  isodiff  : 'iso_P8R2_SOURCE_V6_v06.txt'
  catalogs : ['FL8Y']
  extdir   : '/home/data/1547/fermi/Extended_archive_v18/'
  sources : 
    - { name: '1547', ra : 237.726, dec : -54.3067,
      SpectrumType : 'PLSuperExpCutoff', Index1 : 2.0, Scale : 1000, Prefactor : !!float 1e-12, Index2 : 1.0, Cutoff : 1.0, SpatialModel: 'PointSource' }
   
components:
  - { selection : { evtype : 4  } } # PSF0
  - { selection : { evtype : 8  } } # PSF1
  - { selection : { evtype : 16 } } # PSF2
  - { selection : { evtype : 32 } } # PSF3

fileio:
   outdir : /home/data/1547/fermi/results/

-----------
Running gta.setup()

---------

2018-10-29 18:28:47 INFO    GTAnalysis.setup(): Running setup.
2018-10-29 18:28:47 INFO    GTBinnedAnalysis.setup(): Running setup for component 00
2018-10-29 18:28:47 INFO    GTBinnedAnalysis.run_gtapp(): Running gtselect.
2018-10-29 18:28:47 INFO    GTBinnedAnalysis.run_gtapp(): time -p /home/software/ScienceToolsFermiv11r5p3/x86_64-unknown-linux-gnu-libc2.23/bin/gtselect infile=/home/data/1547/fermi/results/evfile_00.txt outfile=/home/data/1547/fermi/results/ft1_00.fits ra=237.750198364 dec=-54.3819999695 rad=7.57106781187 tmin=239557417.0 tmax=562510675.0 emin=100.0 emax=300000.0 zmin=0.0 zmax=100.0 evclass=128 evclsmin=0 evclsmax=10 evtype=4 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=3 clobber=yes debug=no gui=no mode="ql"
2018-10-29 18:29:41 INFO    GTBinnedAnalysis.run_gtapp(): This is gtselect version ScienceTools-v11r5p3-fssc-20170716
2018-10-29 18:29:41 INFO    GTBinnedAnalysis.run_gtapp(): Applying filter string: ((EVENT_CLASS&o200) != o0) && angsep(RA,DEC,237.7501984,-54.38199997) < 7.571067812 && ((EVENT_TYPE&o4) != o0) && 100 < ENERGY && ENERGY <= 300000 && 239557417 < TIME && TIME <= 562510675 && 0 < ZENITH_ANGLE && ZENITH_ANGLE <= 100 && gtifilter()
2018-10-29 18:29:41 INFO    GTBinnedAnalysis.run_gtapp(): Done.
2018-10-29 18:29:41 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtselect. Execution time: 54.00 s
2018-10-29 18:29:41 INFO    GTBinnedAnalysis.run_gtapp(): Running gtltcube.
2018-10-29 18:29:41 INFO    GTBinnedAnalysis.run_gtapp(): time -p /home/software/ScienceToolsFermiv11r5p3/x86_64-unknown-linux-gnu-libc2.23/bin/gtltcube evfile="/home/data/1547/fermi/results/ft1_00.fits" evtable="EVENTS" scfile=/home/data/1547/fermi/1547sc.fits sctable="SC_DATA" outfile=/home/data/1547/fermi/results/ltcube_00.fits dcostheta=0.025 binsz=1.0 phibins=0 tmin=0.0 tmax=0.0 file_version="1" zmin=0.0 zmax=100.0 chatter=2 clobber=yes debug=no gui=no mode="ql"
2018-10-30 07:20:36 INFO    GTBinnedAnalysis.run_gtapp(): Working on file /home/data/1547/fermi/1547sc.fits
2018-10-30 07:20:36 INFO    GTBinnedAnalysis.run_gtapp(): .....................!
2018-10-30 07:20:36 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtltcube. Execution time: 46254.39 s
/home/anaconda2/lib/python2.7/site-packages/fermipy/irfs.py:51: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  log_ratio = np.log(x[xs1] / x[xs0])
/home/anaconda2/lib/python2.7/site-packages/fermipy/irfs.py:52: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return 0.5 * (y[ys0] * x[xs0] + y[ys1] * x[xs1]) * log_ratio
2018-10-30 07:20:36 INFO    GTBinnedAnalysis.run_gtapp(): Running gtbin.
2018-10-30 07:20:36 INFO    GTBinnedAnalysis.run_gtapp(): time -p /home/software/ScienceToolsFermiv11r5p3/x86_64-unknown-linux-gnu-libc2.23/bin/gtbin evfile=/home/data/1547/fermi/results/ft1_00.fits scfile=/home/data/1547/fermi/1547sc.fits outfile=/home/data/1547/fermi/results/ccube_00.fits algorithm="ccube" ebinalg="LOG" emin=100.0 emax=300000.0 enumbins=28 ebinfile=NONE tbinalg="LIN" tbinfile=NONE nxpix=100 nypix=100 binsz=0.1 coordsys="CEL" xref=237.750198364 yref=-54.3819999695 axisrot=0.0 rafield="RA" decfield="DEC" proj="AIT" hpx_ordering_scheme="RING" hpx_order=3 hpx_ebin=yes hpx_region="" evtable="EVENTS" sctable="SC_DATA" efield="ENERGY" tfield="TIME" chatter=3 clobber=yes debug=no gui=no mode="ql"
2018-10-30 07:20:43 INFO    GTBinnedAnalysis.run_gtapp(): This is gtbin version ScienceTools-v11r5p3-fssc-20170716
2018-10-30 07:20:43 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtbin. Execution time: 6.66 s
2018-10-30 07:20:43 INFO    GTBinnedAnalysis.run_gtapp(): Running gtexpcube2.
2018-10-30 07:20:43 INFO    GTBinnedAnalysis.run_gtapp(): time -p /home/software/ScienceToolsFermiv11r5p3/x86_64-unknown-linux-gnu-libc2.23/bin/gtexpcube2 infile=/home/data/1547/fermi/results/ltcube_00.fits cmap=none outfile=/home/data/1547/fermi/results/bexpmap_00.fits irfs="P8R2_SOURCE_V6" evtype=4 nxpix=360 nypix=180 binsz=1.0 coordsys="CEL" xref=0.0 yref=0.0 axisrot=0.0 proj="CAR" ebinalg="LOG" emin=100.0 emax=300000.0 enumbins=28 ebinfile="NONE" bincalc="EDGE" ignorephi=no thmax=180.0 thmin=0.0 table="EXPOSURE" chatter=3 clobber=yes debug=no mode="ql"
2018-10-30 07:20:50 INFO    GTBinnedAnalysis.run_gtapp(): This is gtexpcube2 version HEAD
2018-10-30 07:20:50 INFO    GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R2_SOURCE_V6 (PSF)
2018-10-30 07:20:50 INFO    GTBinnedAnalysis.run_gtapp(): event_types:  2
2018-10-30 07:20:50 INFO    GTBinnedAnalysis.run_gtapp(): Computing binned exposure map....................!
2018-10-30 07:20:50 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtexpcube2. Execution time: 7.60 s
2018-10-30 07:20:50 INFO    GTBinnedAnalysis.run_gtapp(): Running gtexpcube2.
2018-10-30 07:20:50 INFO    GTBinnedAnalysis.run_gtapp(): time -p /home/software/ScienceToolsFermiv11r5p3/x86_64-unknown-linux-gnu-libc2.23/bin/gtexpcube2 infile=/home/data/1547/fermi/results/ltcube_00.fits cmap=none outfile=/home/data/1547/fermi/results/bexpmap_roi_00.fits irfs="P8R2_SOURCE_V6" evtype=4 nxpix=100 nypix=100 binsz=0.1 coordsys="CEL" xref=237.750198364 yref=-54.3819999695 axisrot=0.0 proj="CAR" ebinalg="LOG" emin=100.0 emax=300000.0 enumbins=28 ebinfile="NONE" bincalc="EDGE" ignorephi=no thmax=180.0 thmin=0.0 table="EXPOSURE" chatter=3 clobber=yes debug=no mode="ql"
2018-10-30 07:20:52 INFO    GTBinnedAnalysis.run_gtapp(): This is gtexpcube2 version HEAD
2018-10-30 07:20:52 INFO    GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R2_SOURCE_V6 (PSF)
2018-10-30 07:20:52 INFO    GTBinnedAnalysis.run_gtapp(): event_types:  2
2018-10-30 07:20:52 INFO    GTBinnedAnalysis.run_gtapp(): Computing binned exposure map....................!
2018-10-30 07:20:52 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtexpcube2. Execution time: 1.44 s
WARNING: FITSFixedWarning: RADECSYS= 'FK5 ' 
the RADECSYS keyword is deprecated, use RADESYSa. [astropy.wcs.wcs]
2018-10-30 07:20:52 INFO    GTBinnedAnalysis.run_gtapp(): Running gtsrcmaps.
2018-10-30 07:20:52 INFO    GTBinnedAnalysis.run_gtapp(): time -p /home/software/ScienceToolsFermiv11r5p3/x86_64-unknown-linux-gnu-libc2.23/bin/gtsrcmaps scfile=/home/data/1547/fermi/1547sc.fits sctable="SC_DATA" expcube=/home/data/1547/fermi/results/ltcube_00.fits cmap=/home/data/1547/fermi/results/ccube_00.fits srcmdl=/home/data/1547/fermi/results/srcmdl_00.xml bexpmap=/home/data/1547/fermi/results/bexpmap_00.fits wmap=none outfile=/home/data/1547/fermi/results/srcmap_00.fits irfs="P8R2_SOURCE_V6" evtype=4 convol=yes resample=yes rfactor=2 minbinsz=0.05 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=3 clobber=yes debug=no gui=no mode="ql"
2018-10-30 07:22:22 INFO    GTBinnedAnalysis.run_gtapp(): This is gtsrcmaps version HEAD
2018-10-30 07:22:22 INFO    GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R2_SOURCE_V6 (PSF)
2018-10-30 07:22:22 INFO    GTBinnedAnalysis.run_gtapp(): event_types:  2
2018-10-30 07:22:22 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named FL8Y J1551.0-5422
2018-10-30 07:22:22 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named 1547
2018-10-30 07:22:22 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named FL8Y J1548.6-5345
.......
........
2018-10-30 07:24:49 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for galdiff....................!
2018-10-30 07:24:49 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for isodiff....................!
2018-10-30 07:24:49 INFO    GTBinnedAnalysis.run_gtapp(): Caught N3tip12TipExceptionE at the top level: Could not open FITS extension "/home/data/1547/fermi/results/srcmap_00.fits[1547]" (CFITSIO ERROR 107: tried to move past end of file)
2018-10-30 07:24:49 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtsrcmaps. Execution time: 237.16 s
2018-10-30 07:24:49 INFO    GTBinnedAnalysis.setup(): Finished setup for component 00
2018-10-30 07:24:49 INFO    GTBinnedAnalysis.setup(): Running setup for component 01
...
...
The rest is as copied in my previous messages.

**Comment by dimauromattia** [comment] 2018-10-30 19:17
Hi @sonnenblu, I found that the origin of the problem is the way you added the source 1547 in the config.yaml. You should use this format to add the source:
sources :
model:
  sources  :
    - { name: 'SourceA', glon : 120.0, glat : -3.0,
        SpectrumType : 'PowerLaw', Index : 2.0, Scale : 1000,
        Prefactor : { value : 1.0, scale : !!float 1e-11, free : '0' },
        SpatialModel: 'PointSource' }
You can change it according to the sed shape you want to use. For more information please visit this page: https://fermipy.readthedocs.io/en/latest/model.html.

**Comment by dimauromattia** [comment] 2018-11-06 14:16
Hi @sonnenblu, is the issue fixed?

**Comment by sonnenblu** [comment] 2018-11-07 12:52
Hi.. not yet unfortunately. I did change the source model although I suspect whether it is the RA/Dec format that is giving me this issue as I had run fermipy analysis before with RA/Dec format and it ran successfully. As you had recommended, I had deleted all old files and re-running the analysis (also fixing the model). But I have a new problem -- the gtltcube is taking forever (like it would run for 2-3 days without giving me any results!). So I had cancelled the job a few times and running again. I will keep you posted on the srcmaps issue once I get past the gtltcube task. Thank you for following up with me and I couldn't comment on the srcmaps issue being fixed due to this reason. Btw, this is how i gave the model now (hoping this is correct):

model:
  src_roiwidth : 15.0
  galdiff  : 'gll_iem_v06.fits'
  isodiff  : 'iso_P8R2_SOURCE_V6_v06.txt'
  catalogs : ['FL8Y']
  extdir   : '/home/data/1547/fermi/Extended_archive_v18/'
  sources : 
    - { name: '1547', glon : 85.3205, glat : 47.5918, SpectrumType : 'PLSuperExpCutoff', Index1 : 1.0, Scale : 1000, Prefactor : !!float 1e-12, Index2 : 1.0, Cutoff : 1.0, SpatialModel: 'PointSource' }

**Comment by dimauromattia** [comment] 2018-11-07 14:37
Hi @sonnenblu, I would suggest to generate the ltcube file externally to Fermipy and directly with the science tools and the command gtltcube. Indeed, the creation of the ltcube file could take a lot of time (even 1 day) and you can run gtltcube in background and wait for the results.

**Comment by sonnenblu** [comment] 2018-11-07 18:06
I got past the gtltcube task and see the same error after the srcmap creation. I have no idea why this is happening..

2018-11-07 11:19:11 INFO    GTBinnedAnalysis.run_gtapp(): Caught N3tip12TipExceptionE at the top level: Could not open FITS extension "/home/data/1547/fermi/results/srcmap_00.fits[1547]" (CFITSIO ERROR 107: tried to move past end of file)

As a last resort, I am going to try again without any sources added to the yaml file to check whether it has to do something with the way I added the model...

**Comment by sonnenblu** [comment] 2018-11-14 14:15
I ran the analysis without adding any sources and didn't get any errors with sourcemap. You are right that the problem lies somewhere in the way I added the source model. I got an error (as mentioned above) after correcting for the model input.. Looks like that is still not the right way.. Do you have an example for adding a PLSuperExpCutoff model? Thank you again for helping me.

**Comment by dimauromattia** [comment] 2018-11-14 16:16
Hi @sonnenblu. Yes I was sure it was the way you added the source because I tried my own. You can use the following to add a PLSuperExpCutoff SED.

sources  :
    - { name: 'SourceB', glon : 300.0, glat : -42.0, SpectrumType : 'PLSuperExpCutoff', Prefactor : { value : 1.0, scale : !!float 1e-07, free : '1', min : !!float 1e-05, max: !!float 1e+05 }, Index1 : { value : -1.7, scale : 1.0, free : '1', min : -5.0, max: 0.0 }, Scale : { value : 1000., scale : 1.0, free : '0', min : 50., max: 10000.0 }, Cutoff : { value : 3000., scale : 1.0, free : '1', min : 500., max: 50000.0 }, Index2 : { value : 1.7, scale : 1.0, free : '1', min : 0.0, max: 5.0 }, SpatialModel: 'PointSource' }

If you think the issue is solved please close it.
Thanks

**Closed** 2018-11-15 01:32 UTC

**Comment by sunanda15** [comment] 2022-08-03 06:39
Hi, I am facing the indexError. Please guide me.
ScienceTools version 2.0.8
2022-08-03 12:00:00 INFO    GTAnalysis.setup(): Running setup.
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.setup(): Running setup for component 00
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): Running gtselect.
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtselect infile=/home/sunanda/mkn421/lightcurve1/evfile_00.txt outfile=/home/sunanda/mkn421/lightcurve1/ft1_00.fits ra=77.35929870605469 dec=5.701399803161621 rad=1.2071067811865475 tmin=520560005.0 tmax=567993605.0 emin=500.0 emax=100000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=3 clobber=yes debug=no gui=no mode="ql"
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): This is gtselect version HEAD
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): Fatal in <TROOT::InitInterpreter>: cannot load library /home/sunanda/root/root-6.20.04-install/lib/libRIO.so: undefined symbol: _ZN6TClass8GetClassERKSt9type_infobb
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtselect. Execution time: 0.09 s
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): Running gtltcube.
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtltcube evfile="/home/sunanda/mkn421/lightcurve1/ft1_00.fits" evtable="EVENTS" scfile=L220803020958D7616F2375_SC00.fits sctable="SC_DATA" outfile=/home/sunanda/mkn421/lightcurve1/ltcube_00.fits dcostheta=0.025 binsz=1.0 phibins=0 tmin=0.0 tmax=0.0 file_version="1" zmin=0.0 zmax=90.0 chatter=2 clobber=yes debug=no gui=no mode="ql"
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): Caught St13runtime_error at the top level: File not found: 
/home/sunanda/mkn421/lightcurve1/ft1_00.fits
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtltcube. Execution time: 0.11 s
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    gta.setup()
  File "/home/sunanda/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 1082, in setup
    c.setup(overwrite=overwrite)
  File "/home/sunanda/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 5121, in setup
    self._ltc = LTCube.create(self.files['ltcube'])
  File "/home/sunanda/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermipy/ltcube.py", line 192, in create
    ltc = cls.create_from_fits(files[0])
IndexError: list index out of range

**Comment by TheCriticalSpan** [comment] 2023-06-19 12:25
@sunanda15 Did you ever fix your IndexError issue? I am running into the same exact thing right now. Tried updating fermitools through mamba but it doesn't seem to be fixing anything
