### ISSUE TITLE
Reference/API empty in docs

### ISSUE THREAD

**Issue by jefemagril** [fermiPy/fermipy#71] opened 2016-08-08 19:23 UTC
Somehow the doc pages are not generating anything under the "Reference/API" sections anymore. For example,
http://fermipy.readthedocs.io/en/latest/advanced/sed.html#reference-api
Any idea why?

**Comment by woodmd** [comment] 2016-08-10 23:58
This is now fixed.  This was a recurring issue caused by the fact that every external module and submodule needed to be explicitly defined as a mock module in `docs/conf.py`.  I've now switched over to RTD's new conda build feature so hopefully this will prevent further occurrences of this issue.  For future reference if the RTD build for the "latest" has failed for some reason you can always refer to the docs page for one of the tagged releases, e.g.

http://fermipy.readthedocs.io/en/0.10.3/

**Closed by woodmd** 2016-08-10 23:58 UTC
