### ISSUE TITLE
Error when loading 3FGL

### ISSUE THREAD

**Issue by kialio** [fermiPy/fermipy#173] opened 2018-01-29 18:16 UTC
Hi, 

Testing a new release of the STs at the FSSC and seeing this error when loading the 3FGL catalog.  I'll poke at this when I have a spare moment but thought I'd post it in case others can have time.

`from fermipy import roi_model`

`roi_model.catalog.Catalog3FGL(fitsfile='gll_psc_v16.fit')`

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-10-e1381c848964> in <module>()
> ----> 1 roi_model.catalog.Catalog3FGL(fitsfile='gll_psc_v16.fit')
> 
> $FERMI_DIR/lib/python2.7/site-packages/fermipy/catalog.pyc in __init__(self, fitsfile, extdir)
>     255         table.sort('Source_Name')
>     256 
> --> 257         super(Catalog3FGL, self).__init__(table, extdir)
>     258 
>     259         m = self.table['SpectrumType'] == 'PLExpCutoff'
> 
> $FERMI_DIR/lib/python2.7/site-packages/fermipy/catalog.pyc in __init__(self, table, extdir)
>     109         self._radec = np.vstack((self._src_skydir.ra.deg,
>     110                                  self._src_skydir.dec.deg)).T
> --> 111         self._glonlat = np.vstack((self._src_skydir.galactic.l.deg,
>     112                                    self._src_skydir.galactic.b.deg)).T
>     113 
> 
> $FERMI_DIR/lib/python2.7/site-packages/astropy/coordinates/sky_coordinate.pyc in __getattr__(self, attr)
>     491             frame_cls = frame_transform_graph.lookup_name(attr)
>     492             if frame_cls is not None and self.frame.is_transformable_to(frame_cls):
> --> 493                 return self.transform_to(attr)
>     494 
>     495         # Fail
> 
> $FERMI_DIR/lib/python2.7/site-packages/astropy/coordinates/sky_coordinate.pyc in transform_to(self, frame, merge_attributes)
>     446         # Do the transformation, returning a coordinate frame of the desired
>     447         # final type (not generic).
> --> 448         new_coord = trans(self.frame, generic_frame)
>     449 
>     450         # Finally make the new SkyCoord object from the `new_coord` and
> 
> $FERMI_DIR/lib/python2.7/site-packages/astropy/coordinates/transformations.pyc in __call__(self, fromcoord, toframe)
>     902 
>     903             curr_toframe = t.tosys(**frattrs)
> --> 904             curr_coord = t(curr_coord, curr_toframe)
>     905 
>     906         # this is safe even in the case where self.transforms is empty, because
> 
> $FERMI_DIR/lib/python2.7/site-packages/astropy/coordinates/transformations.pyc in __call__(self, fromcoord, toframe)
>     815 
>     816         rep = fromcoord.represent_as(CartesianRepresentation)
> --> 817         newrep = rep.transform(transform_matrix)
>     818 
>     819         if issubclass(fromcoord.data.__class__, UnitSphericalRepresentation):
> 
> $FERMI_DIR/lib/python2.7/site-packages/astropy/coordinates/representation.pyc in transform(self, matrix)
>     601             # Matrix multiply all pmat items and coordinates, broadcasting the
>     602             # remaining dimensions.
> --> 603             newxyz = np.einsum('...ij,j...->i...', matrix, oldxyz.value)
>     604 
>     605         newxyz = u.Quantity(newxyz, oldxyz.unit, copy=False)
> 
> $FERMI_DIR/lib/python2.7/site-packages/numpy/core/einsumfunc.pyc in einsum(*operands, **kwargs)
>    1085     # Build the contraction list and operand
>    1086     operands, contraction_list = einsum_path(*operands, optimize=optimize_arg,
> -> 1087                                              einsum_call=True)
>    1088 
>    1089     handle_out = False
> 
> $FERMI_DIR/lib/python2.7/site-packages/numpy/core/einsumfunc.pyc in einsum_path(*operands, **kwargs)
>     686 
>     687     # Python side parsing
> --> 688     input_subscripts, output_subscript, operands = _parse_einsum_input(operands)
>     689     subscripts = input_subscripts + '->' + output_subscript
>     690 
> 
> $FERMI_DIR/lib/python2.7/site-packages/numpy/core/einsumfunc.pyc in _parse_einsum_input(operands)
>     430                     subscripts += einsum_symbols[s]
>     431                 else:
> --> 432                     raise TypeError("For this input type lists must contain "
>     433                                     "either int or Ellipsis")
>     434             if num != last:
> 
> TypeError: For this input type lists must contain either int or Ellipsis
>

**Comment by woodmd** [comment] 2018-01-29 18:31
This is a known issue caused by an interaction between astropy and the most recent version of numpy.  There was supposed to be a patch release for numpy coming out soon.  Your options would be to wait for that or try downgrading your numpy version.

**Comment by kialio** [comment] 2018-01-29 18:32
Got it.  I tried to downgrade astropy but not numpy.  I hadn't dug into it much.  I'll do that.

**Comment by woodmd** [comment] 2018-02-16 19:49
Looks like you can resolve this now by installing the latest astropy release (2.0.4).

**Comment by dimauromattia** [comment] 2018-02-18 16:45
I had the same issue with astropy release 2.0.3 and I confirm that with 2.0.4 the issue is resolved

**Comment by woodmd** [comment] 2018-03-01 00:56
numpy 1.14.1 is also out now so I think we can close this issue.

**Closed by woodmd** 2018-03-01 00:56 UTC
