### ISSUE TITLE
problem with gta.fit

### ISSUE THREAD

**Issue by astrolog1986** [fermiPy/fermipy#169] opened 2017-12-11 21:03 UTC
Dear all,

In the analyses when NewMinuit optimizer is  used, after the command gta.fit()
it gives an error
<<
Traceback (most recent call last):
  File "/home/yerevan2/miniconda/envs/fermi-env/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2798, in _fit_optimizer
    self.like.fit(**kw)
  File "/opt/Fermi/x86_64-unknown-linux-gnu-libc2.5/lib/python/SummedLikelihood.py", line 95, in fit
    optObject=optObject)
  File "/opt/Fermi/x86_64-unknown-linux-gnu-libc2.5/lib/python/SummedLikelihood.py", line 184, in _errors
    myOpt.find_min(verbosity, tol, self.tolType)
  File "/opt/Fermi/x86_64-unknown-linux-gnu-libc2.5/lib/python/pyLikelihood.py", line 2442, in find_min
    return lib_pyLikelihood.NewMinuit_find_min(*args)
RuntimeError: Minuit abnormal termination.  No convergence?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yerevan2/miniconda/envs/fermi-env/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2931, in fit
    fit_output = self._fit(**config)
  File "/home/yerevan2/miniconda/envs/fermi-env/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2843, in _fit
    return self._fit_optimizer_iter(**kwargs)
  File "/home/yerevan2/miniconda/envs/fermi-env/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2771, in _fit_optimizer_iter
    o['errors'][i] = p['error']
IndexError: index 2 is out of bounds for axis 0 with size 2
>>
Instead if for the same analysis is done with Minuit it works without a problem.
Can you please advise how to solve this issue.

**Comment by TarekHC** [comment] 2017-12-15 08:37
Hi all, 

I have been encountering the same error several times these days, although I always assumed it is caused by the fit/optimization not converging.

Although I can confirm one thing: the problem is not only associated to MINUIT. I encountered it a couple of times using NEWMINUIT, in the optimization step:

```python
2017-12-14 19:34:42 INFO    GTAnalysis.optimize(): Starting
[PATH]/miniconda/lib/python2.7/site-packages/scipy/interpolate/fitpack2.py:226: UserWarning: 
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  warnings.warn(message)
Plotter is MatPlotlib
Attempt to set the value outside of existing bounds.
Value nan is not between 1e-05 and 1000
2017-12-14 19:36:47 ERROR   GTAnalysis._fit_optimizer(): Likelihood optimization failed.
Traceback (most recent call last):
  File "[PATH]/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2625, in _fit_optimizer
    self.like.fit(**kw)
  File "[PATH]/lat-st/lib/python/SummedLikelihood.py", line 95, in fit
    optObject=optObject)
  File "[PATH]/lat-st/lib/python/SummedLikelihood.py", line 184, in _errors
    myOpt.find_min(verbosity, tol, self.tolType)
  File "[PATH]/lat-st/lib/python/pyLikelihood.py", line 2442, in find_min
    return lib_pyLikelihood.NewMinuit_find_min(*args)
RuntimeError: Attempt to set the value outside of existing bounds.
Attempt to set the value outside of existing bounds.
Value nan is not between 1e-05 and 1000
2017-12-14 19:36:47 ERROR   GTAnalysis._fit_optimizer(): Likelihood optimization failed.
Traceback (most recent call last):
  File "[PATH]/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2625, in _fit_optimizer
    self.like.fit(**kw)
  File "[PATH]/lat-st/lib/python/SummedLikelihood.py", line 95, in fit
    optObject=optObject)
  File "[PATH]/lat-st/lib/python/SummedLikelihood.py", line 184, in _errors
    myOpt.find_min(verbosity, tol, self.tolType)
  File "[PATH]/lat-st/lib/python/pyLikelihood.py", line 2442, in find_min
    return lib_pyLikelihood.NewMinuit_find_min(*args)
RuntimeError: Attempt to set the value outside of existing bounds.
Attempt to set the value outside of existing bounds.
Value nan is not between 1e-05 and 1000
2017-12-14 19:36:47 ERROR   GTAnalysis._fit_optimizer(): Likelihood optimization failed.
Traceback (most recent call last):
  File "[PATH]/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2625, in _fit_optimizer
    self.like.fit(**kw)
  File "[PATH]/lat-st/lib/python/SummedLikelihood.py", line 95, in fit
    optObject=optObject)
  File "[PATH]/lat-st/lib/python/SummedLikelihood.py", line 184, in _errors
    myOpt.find_min(verbosity, tol, self.tolType)
  File "[PATH]/lat-st/lib/python/pyLikelihood.py", line 2442, in find_min
    return lib_pyLikelihood.NewMinuit_find_min(*args)
RuntimeError: Attempt to set the value outside of existing bounds.
Traceback (most recent call last):
  File "run_LP.py", line 38, in <module>
    gta.optimize()
  File "[PATH]/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2129, in optimize
    self.fit(loglevel=logging.DEBUG, **config['optimizer'])
  File "[PATH]/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2758, in fit
    fit_output = self._fit(**config)
  File "[PATH]/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2670, in _fit
    return self._fit_optimizer_iter(**kwargs)
  File "[PATH]/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2598, in _fit_optimizer_iter
    o['errors'][i] = p['error']
IndexError: index 2 is out of bounds for axis 0 with size 2
```

**Comment by woodmd** [comment] 2017-12-15 17:20
I believe @astrolog1986 was reporting this issue with NEWMINUIT.  Did you find an instance where the same error occurred for MINUIT?

It looks this is a bug I fixed in master but didn't yet tag.  We're long overdue for a new release so I can try to get one out in the next few weeks.  In the meantime you can install the master branch from github with:

`pip install git+https://github.com/fermiPy/fermipy.git`

**Comment by TarekHC** [comment] 2017-12-15 17:27
> I believe @astrolog1986 was reporting this issue with NEWMINUIT. Did you find an instance where the same error occurred for MINUIT?

Oh, sorry, I copy pasted (and refered) to the wrong output. Indeed, I see the same error with MINUIT:

```python
2017-12-15 17:17:28 INFO    GTAnalysis.optimize(): Starting
[PATH]/miniconda/lib/python2.7/site-packages/scipy/interpolate/fitpack2.py:226: UserWarning: 
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  warnings.warn(message)
2017-12-15 17:27:23 ERROR   GTAnalysis._fit_optimizer(): Likelihood optimization failed.
Traceback (most recent call last):
  File "[PATH]/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2625, in _fit_optimizer
    self.like.fit(**kw)
  File "[PATH]/lat-st/lib/python/SummedLikelihood.py", line 95, in fit
    optObject=optObject)
  File "[PATH]/lat-st/lib/python/SummedLikelihood.py", line 184, in _errors
    myOpt.find_min(verbosity, tol, self.tolType)
  File "[PATH]/lat-st/lib/python/pyLikelihood.py", line 2304, in find_min
    return lib_pyLikelihood.Minuit_find_min(*args)
RuntimeError: Attempt to set the value outside of existing bounds.
2017-12-15 17:27:24 ERROR   GTAnalysis._fit_optimizer(): Likelihood optimization failed.
Traceback (most recent call last):
  File "[PATH]/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2625, in _fit_optimizer
    self.like.fit(**kw)
  File "[PATH]/lat-st/lib/python/SummedLikelihood.py", line 95, in fit
    optObject=optObject)
  File "[PATH]/lat-st/lib/python/SummedLikelihood.py", line 184, in _errors
    myOpt.find_min(verbosity, tol, self.tolType)
  File "[PATH]/lat-st/lib/python/pyLikelihood.py", line 2304, in find_min
    return lib_pyLikelihood.Minuit_find_min(*args)
RuntimeError: Attempt to set the value outside of existing bounds.
2017-12-15 17:27:24 ERROR   GTAnalysis._fit_optimizer(): Likelihood optimization failed.
Traceback (most recent call last):
  File "[PATH]/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2625, in _fit_optimizer
    self.like.fit(**kw)
  File "[PATH]/lat-st/lib/python/SummedLikelihood.py", line 95, in fit
    optObject=optObject)
  File "[PATH]/lat-st/lib/python/SummedLikelihood.py", line 184, in _errors
    myOpt.find_min(verbosity, tol, self.tolType)
  File "[PATH]/lat-st/lib/python/pyLikelihood.py", line 2304, in find_min
    return lib_pyLikelihood.Minuit_find_min(*args)
RuntimeError: Attempt to set the value outside of existing bounds.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-1-bd3cf83ae454> in <module>()
     41                                 'SpatialModel': 'PointSource'})
     42 
---> 43 gta.optimize()

[PATH]/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.pyc in optimize(self, **kwargs)
   2127             self.logger.debug('Fitting shape %s TS: %10.3f', s.name, s['ts'])
   2128             self.free_source(s.name, loglevel=logging.DEBUG)
-> 2129             self.fit(loglevel=logging.DEBUG, **config['optimizer'])
   2130             self.free_source(s.name, free=False, loglevel=logging.DEBUG)
   2131 

[PATH]/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.pyc in fit(self, update, **kwargs)
   2756         saved_state = LikelihoodState(self.like)
   2757 
-> 2758         fit_output = self._fit(**config)
   2759         o.update(fit_output)
   2760 

[PATH]/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.pyc in _fit(self, **kwargs)
   2668             return self._fit_newton(**kwargs)
   2669         else:
-> 2670             return self._fit_optimizer_iter(**kwargs)
   2671 
   2672     def fit(self, update=True, **kwargs):

[PATH]/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.pyc in _fit_optimizer_iter(self, **kwargs)
   2596         for i, p in enumerate(free_params):
   2597             o['values'][i] = p['value']
-> 2598             o['errors'][i] = p['error']
   2599             o['indices'][i] = p['idx']
   2600             o['src_names'][i] = p['src_name']

IndexError: index 2 is out of bounds for axis 0 with size 2
```

**Comment by TarekHC** [comment] 2017-12-20 14:36
Hi @woodmd @astrolog1986 

I can confirm that by going to the github version "0.15.1+61.g5e03" I managed to properly optimize/fit the same model which I could not with the release version (I was getting this same error either with `MINUIT` or `NEWMINUIT`). Note that the fit was correct with an identical model (so it was probably not just the exception handling that changed?).

I will run a large number of analyses during the next few days, so I might report again, but in principle I think we could close this issue.

**Comment by woodmd** [comment] 2017-12-29 18:25
Just a heads up -- I've pushed a new release (0.16.0) that includes the commits that resolve this issue.

**Comment by woodmd** [comment] 2018-01-09 18:19
Closing this issue now since it should be resolved in the latest release.

**Closed by woodmd** 2018-01-09 18:19 UTC

**Comment by henrikef** [comment] 2022-06-14 21:33
@nyctophile-aayu This is the issue tracker for `fermipy`, a community-contributed analysis framework. For issues with the fermi tools themselves, please contact the FSSC (Fermi Science Support Center) helpdesk.
