### ISSUE TITLE
Error in generating TS map/localization

### ISSUE THREAD

**Issue by vaidehiratna** [fermiPy/fermipy#38] opened 2016-06-12 22:14 UTC
Hi,
I am trying to localize the coordinates of a source. My input is as follows
gta.localize(name='%s'%(srcname),dtheta_max=0.5,nstep=5,update=True)

Unfortunately, it gives the following error
Traceback (most recent call last):
  File "/u/gl/vaidehi/code_TSMAP2.py", line 218, in <module>
    main(sys.argv)
  File "/u/gl/vaidehi/code_TSMAP2.py", line 141, in main
    local = gta.localize(name='%s'%(srcname),dtheta_max=0.5,nstep=5,update=True)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.8.0+22.g11ac-py2.7.egg/fermipy/sourcefind.py", line 505, in localize
    coordsys=wcs_utils.get_coordsys(skywcs))
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.8.0+22.g11ac-py2.7.egg/fermipy/skymap.py", line 146, in create
    cdelt,crpix)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.8.0+22.g11ac-py2.7.egg/fermipy/wcs_utils.py", line 91, in create_wcs
    w = pywcs.WCS(w.to_header())
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.10/lib/python2.7/site-packages/astropy/wcs/wcs.py", line 448, in **init**
    self.wcs.set()
astropy.wcs._wcs.InvalidTransformError: ERROR 7 in wcsset() at line 1760 of file cextern/wcslib/C/wcs.c:
Ill-conditioned coordinate transformation parameters.
ERROR 4 in celset() at line 399 of file cextern/wcslib/C/cel.c:
Ill-conditioned coordinate transformation parameters
No valid solution for latp for these values of phip, phi0, and theta0.

The ra,dec values of the object are 61.64296, 6.62083 degrees, respectively. The same command has worked for more than 100 sources and I am unable to understand this error.
Please help.
Thanks
Vaidehi

**Comment by woodmd** [comment] 2016-06-15 17:57
If you send me the path to you analysis directory I can have a closer look at this.  You might also try rerunning with the latest tag (0.9.2).

**Comment by vaidehiratna** [comment] 2016-06-16 02:18
Here is the path of the script
/u/gl/vaidehi/CGRABS/code_TSMAP2.py
The source name, ra, and dec is given in the 'Det_remain.txt' file in the same folder.
The log file is kept in the following path
/u/gl/vaidehi/CGRABS/CGRABSJ0406+0637/logfile.txt

The source of interest is not present in 3FGL and thus, the logic of the work is to (i) first perform a crude fitting at the radio position of the object, remove it from the model and then search for TS peaks to determine the nearest TS peak, and (ii) perform a further second round of analysis at the TS peak position, include all the unmodeled sources, optimize the source coordinates, and perform the final fitting to get the spectral parameters. First step is being done using 'code_TSMAP.py' script (successfully completed) and second with 'code_TSMAP2.py'. Both scripts are kept in the above mentioned folder.
Since I used the same 0.8.0 version for remaining >100 objects, I feel it would be great if for this object also I can finish the analysis before upgrading to 0.9.2.

The files generated after step 1 are kept at
/u/gl/vaidehi/fermi_disk/CGRABS_NO_GAMMA/Round1/CGRABSJ0406+0637

Please let me know if you need more information.
Thanks.

**Comment by woodmd** [comment] 2016-06-30 08:36
I've tried running your analysis with the latest version of fermipy but didn't succeed in reproducing the error.  Unfortunately I can't easily patch older versions of the code so I think your best option would be to try running with the current HEAD version.  For the most part I've tried to make the ROI files forward-compatible so that you should be able to restore the state of the analysis even when using files generated with an older release of the code.

**Comment by vaidehiratna** [comment] 2016-07-08 22:42
Hi,
I tried again with updated fermipy 0.9.2 but it looks like something to do with astropy wcs, but I'm no expert. Here is the log
>>> local = gta.localize(name='%s'%(srcname),dtheta_max=0.5,nstep=5,update=True)
2016-07-08 15:36:25 INFO     GTAnalysis.localize(): Running localization for CGRABSJ0406+0637
2016-07-08 15:36:34 INFO     GTAnalysis.tsmap(): Generating TS map
2016-07-08 15:37:07 INFO     GTAnalysis.add_source(): Adding source tsmap_testsource
Generating SourceMap for tsmap_testsource....................!
Generating SourceMap for tsmap_testsource....................!
Generating SourceMap for tsmap_testsource....................!
Generating SourceMap for tsmap_testsource....................!
2016-07-08 15:37:22 INFO     GTAnalysis.delete_source(): Deleting source tsmap_testsource
/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.9.2+43.g83a2-py2.7.egg/fermipy/tsmap.py:736: RuntimeWarning: invalid value encountered in greater
  mx = mm[j,ix, :] > mm[j,ix,iy] * threshold
2016-07-08 15:37:25 INFO     GTAnalysis.tsmap(): Finished TS map
/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.9.2+43.g83a2-py2.7.egg/fermipy/utils.py:533: RuntimeWarning: invalid value encountered in double_scalars
  rchi2 = np.sum(df**2)/len(fm)
2016-07-08 15:37:25 INFO     GTAnalysis.free_source(): Freeing parameters for CGRABSJ0406+0637      : ['Prefactor']
2016-07-08 15:37:45 INFO     GTAnalysis.free_source(): Fixing parameters for CGRABSJ0406+0637      : ['Prefactor']
WARNING: FITSFixedWarning: 'celfix' made the change 'Ill-conditioned coordinate transformation parameters'. [astropy.wcs.wcs]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.9.2+43.g83a2-py2.7.egg/fermipy/sourcefind.py", line 525, in localize
    coordsys=wcs_utils.get_coordsys(skywcs))
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.9.2+43.g83a2-py2.7.egg/fermipy/skymap.py", line 146, in create
    cdelt,crpix)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.9.2+43.g83a2-py2.7.egg/fermipy/wcs_utils.py", line 147, in create_wcs
    w = pywcs.WCS(w.to_header())
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.10/lib/python2.7/site-packages/astropy/wcs/wcs.py", line 448, in __init__
    self.wcs.set()
astropy.wcs._wcs.InvalidTransformError: ERROR 7 in wcsset() at line 1760 of file cextern/wcslib/C/wcs.c:
Ill-conditioned coordinate transformation parameters.
ERROR 4 in celset() at line 399 of file cextern/wcslib/C/cel.c:
Ill-conditioned coordinate transformation parameters
No valid solution for latp for these values of phip, phi0, and theta0.

Thanks.

**Comment by woodmd** [comment] 2016-07-13 18:32
It appears that the localization is failing somehow and setting the new position to an invalid coordinate.  I thought that I had implemented cross-checks in the code to prevent this from happening but I'll try to have another look.  Should I use the directory you originally pointed me to for testing?

**Comment by vaidehiratna** [comment] 2016-07-13 18:46
Yes, sure. Please use the files as necessary.

**Comment by woodmd** [comment] 2016-12-09 23:26
Closing because I never managed to reproduce this issue.

**Closed by woodmd** 2016-12-09 23:26 UTC
