### ISSUE TITLE
light curve bin issue

### ISSUE THREAD

**Issue by phvergara** [fermiPy/fermipy#362] opened 2020-09-23 02:39 UTC
Hi, I was running fermipy analysis to mrk 421 without problems to generate a light curve, but in time range [545586217,546191017] the analysis fail and stop. The bin that fail matches the flag reported by Fermi-Lat in March, 2018 when the instrument power off any days. The terminal show me the next message (I attach the full log as fermipy2.log):

2020-09-22 21:59:13 INFO    lightcurve_545586217_546191017 GTBinnedAnalysis.write_xml(): Writing /home/philipe/mark2/kk/lightcurve_545586217_546191017/base_00.xml...
Joint fit  ['4FGL J1104.4+3812', '4FGL J1112.5+3448', '4FGL J1127.8+3618', '4FGL J1131.0+3815', '4FGL J1106.7+3623']
Fitting shape 4FGL J1104.4+3812 TS:     77.468
2020-09-22 21:59:18 INFO    lightcurve_545586217_546191017 GTBinnedAnalysis.write_xml(): Writing /home/philipe/mark2/kk/lightcurve_545586217_546191017/fit_model_final_00.xml...
2020-09-22 21:59:21 INFO    lightcurve_545586217_546191017 GTAnalysis._process_lc_bin(): Finished time range 545586217 546191017
Traceback (most recent call last):
  File "run.py", line 35, in <module>
    lc = gta.lightcurve('mkn421',free_radius=3.0,time_bins=[544981417,545586217,545586217+86400*7],multithread=True,nthread=4,use_scaled_srcmap=True,outdir='kk')
  File "/home/philipe/Escritorio/miniconda/envs/fermipy/lib/python2.7/site-packages/fermipy/lightcurve.py", line 289, in lightcurve
    o = self._make_lc(name, **config)
  File "/home/philipe/Escritorio/miniconda/envs/fermipy/lib/python2.7/site-packages/fermipy/lightcurve.py", line 450, in _make_lc
    if not mapo[i]['fit_success']:
KeyError: 'fit_success'
>>>>

-----------------------------------------------------------------------------------------------------------------------------------

The log of the bin show me the next message (I attach as fermipybin.log):

-------------------------------------------------------------------------------------------------------------------------------------

2020-09-22 21:58:15 INFO    lightcurve_544981417_545586217 GTAnalysis._process_lc_bin(): Fitting time range 544981417 545586217
2020-09-22 21:58:15 DEBUG   lightcurve_544981417_545586217 GTAnalysis.setup(): Running setup.
2020-09-22 21:58:15 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.setup(): Running setup for component 00
2020-09-22 21:58:15 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis._select_data(): Skipping data selection.
2020-09-22 21:58:15 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis._create_ltcube(): Skipping LT Cube.
2020-09-22 21:58:15 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.setup(): Loading LT Cube /home/philipe/mark2/kk/lightcurve_544981417_545586217/ltcube_00.fits
2020-09-22 21:58:15 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.setup(): Creating PSF model
2020-09-22 21:58:17 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis._bin_data(): Skipping gtbin.
2020-09-22 21:58:17 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): Running gtexpcube2.
2020-09-22 21:58:17 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): time -p gtexpcube2 infile=/home/philipe/mark2/kk/lightcurve_544981417_545586217/ltcube_00.fits cmap=none outfile=/home/philipe/mark2/kk/lightcurve_544981417_545586217/bexpmap_00.fits irfs="P8R3_SOURCE_V2" evtype=3 edisp_bins=-1 nxpix=360 nypix=180 binsz=1.0 coordsys="CEL" xref=0.0 yref=0.0 axisrot=0.0 proj="CAR" ebinalg="LOG" emin=100.0 emax=300000.0 enumbins=28 ebinfile="NONE" hpx_ordering_scheme="RING" hpx_order=6 bincalc="EDGE" ignorephi=no thmax=180.0 thmin=0.0 table="EXPOSURE" chatter=3 clobber=yes debug=no mode="ql"
2020-09-22 21:58:30 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): 
2020-09-22 21:58:30 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).
2020-09-22 21:58:30 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): 
2020-09-22 21:58:30 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): This is gtexpcube2 version HEAD
2020-09-22 21:58:30 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): Using evtype=3 (i.e., FRONT/BACK irfs)
2020-09-22 21:58:30 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R3_SOURCE_V2
2020-09-22 21:58:30 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): event_types:  0  1
2020-09-22 21:58:30 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): Computing binned exposure map.................Caught St13runtime_error at the top level: ExposureCube::value: exposure < 0
2020-09-22 21:58:30 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): Finished gtexpcube2. Execution time: 13.41 s
2020-09-22 21:58:30 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): Running gtexpcube2.
2020-09-22 21:58:30 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): time -p gtexpcube2 infile=/home/philipe/mark2/kk/lightcurve_544981417_545586217/ltcube_00.fits cmap=none outfile=/home/philipe/mark2/kk/lightcurve_544981417_545586217/bexpmap_roi_00.fits irfs="P8R3_SOURCE_V2" evtype=3 edisp_bins=0 nxpix=100 nypix=100 binsz=0.1 coordsys="CEL" xref=166.11869812 yref=38.2070007324 axisrot=0.0 proj="CAR" ebinalg="LOG" emin=100.0 emax=300000.0 enumbins=28 ebinfile="NONE" hpx_ordering_scheme="RING" hpx_order=6 bincalc="EDGE" ignorephi=no thmax=180.0 thmin=0.0 table="EXPOSURE" chatter=3 clobber=yes debug=no mode="ql"
2020-09-22 21:58:34 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): 
2020-09-22 21:58:34 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).
2020-09-22 21:58:34 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): 
2020-09-22 21:58:34 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): This is gtexpcube2 version HEAD
2020-09-22 21:58:34 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): Using evtype=3 (i.e., FRONT/BACK irfs)
2020-09-22 21:58:34 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R3_SOURCE_V2
2020-09-22 21:58:34 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): event_types:  0  1
2020-09-22 21:58:34 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): Computing binned exposure map....................!
2020-09-22 21:58:34 DEBUG   lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): Finished gtexpcube2. Execution time: 3.18 s

---------------------------------------------------------------------------------------------------------------------------------

I found the next issue lightcurve_544981417_545586217 GTBinnedAnalysis.run_gtapp(): **Computing binned exposure map.................Caught St13runtime_error at the top level: ExposureCube::value: exposure < 0**. Then I checked the folder for the bin and the file bexpmap_00.fits was not generated, so I think that for this reason the program stop because the file is necessary for the analysis.  I tried to create this file mannually but i didnt have success, maybe a type of exception can be included when files fail by a flag event and continue with next bin.

[analysis.zip](https://github.com/fermiPy/fermipy/files/5265211/analysis.zip)

**Comment by eacharles** [comment] 2021-03-11 20:48
Sorry for the slow reply.  This is most likely because the instrument was off for that time range.   We should update the code for fail gracefully when this is the case.

**Comment by jeget** [comment] 2021-03-19 04:09
I would like to comment on the problem of lightcurve failure because of a single bin. It is mentioned in a number of issues, e.g. #381 and earlier ones. I encountered this problem, too. It persists in version 1.0.1. In my view, there are two things to be fixed.

1. `setup()` is called in the method `_process_lc_bin()` of the lightcurve.py module which in turn is called from the `_make_lc()` method:
https://github.com/fermiPy/fermipy/blob/2a06947c71ab1b731e84fa45a5c41b83769bf7c7/fermipy/lightcurve.py#L450
Now, if setup fails then the except block is executed and `_process_lc_bin()` returns an empty dictionary:
https://github.com/fermiPy/fermipy/blob/2a06947c71ab1b731e84fa45a5c41b83769bf7c7/fermipy/lightcurve.py#L154-L163
This empty dictionary is assigned to `next_fit` in `_make_lc()`, but then, in the line 452, we see
https://github.com/fermiPy/fermipy/blob/2a06947c71ab1b731e84fa45a5c41b83769bf7c7/fermipy/lightcurve.py#L452
which, with `next_fit` dictionary empty, naturally causes the 'fit_success' KeyError.
The minimal and straightforward workaround I found is to initialize the return dictionary: in the above piece, I changed `return {}` to `return {'fit_success': False}`.
2. Sometimes `setup()` can be interrupted by a segmentation fault. It can happen if the time bin contains no observations (no GTIs). The backtrace I found is the following:
```
fermipy/lightcurve.py(289)lightcurve()
-> o = self._make_lc(name, **config)
fermipy/lightcurve.py(450)_make_lc()
-> next_fit = next(mapo)
fermipy/lightcurve.py(158)_process_lc_bin()
-> gta.setup()
fermipy/gtanalysis.py(1085)setup()
-> self._create_likelihood()
fermitpy/gtanalysis.py(1112)_create_likelihood()
-> c._create_binned_analysis(srcmdl)
fermipy/gtanalysis.py(5402)_create_binned_analysis()
-> self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
fermitools/BinnedAnalysis.py(71)__init__()
-> self._createObservation(srcMaps, expCube, self.irfs)
fermitools/BinnedAnalysis.py(78)_createObservation()
-> self._roiCuts.readCuts(srcMaps, "", False)
```
This `readCuts()` method  where segfault happens is in pylikelihood package and seems to be precompiled, I can't get into it.
I cannot say for sure, but I think the problem is in zero exposure. In `gtanalysis.setup` method, line 5128, a PSF object is created which contains an exposure array. I decided to raise an error if all the elements of this array are zeros. So, in irfs.py, after line 567, I added the following:
```
if sum(sum(np.abs(exp))) == 0:
    raise RuntimeError('irfs.py(569): Zero exposure!')
```
Maybe it's not a good idea, but a bin with zero exposure is no good anyways while my analysis now continues normally with 'Analisys failed in time bin' message.

**Closed** 2022-06-27 19:19 UTC

**Comment by spletts** [comment] 2023-12-08 18:25
@eacharles @henrikef For what reasons other than the instrument being offline would the `lightcurve` analysis fail? 
I am using fermipy version v1.1.6 & ScienceTools version 2.2.0, so `lightcurve` fails gracefully and skips over empty bins with the message:
```
(<class 'RuntimeError'>, RuntimeError('irfs.py(569): Zero exposure!'), <traceback object at 0x7fe60676ecc0>)
Analysis failed in time range 631324805 631411205 
```
I am using 1-day bins, and all the bins in the following range are empty: 630374405 to 632016005 MET = 2020-12-23 to 2021-01-11. I don't see any [news](https://fermi.gsfc.nasa.gov/ssc/library/news/) about Fermi being offline during this time. The photon event files have GTIs during this range of dates. The [Light Curve Repository](https://fermi.gsfc.nasa.gov/ssc/data/access/lat/LightCurveRepository/source.html?source_name=4FGL_J0650.7+2503#) for the source does not show any gaps.
What are some reasons the analysis would fail?
