### ISSUE TITLE
matplotlib error

### ISSUE THREAD

**Issue by ktzhao** [fermiPy/fermipy#19] opened 2016-03-13 02:37 UTC
Dear fermipy team,

I have installed the fermipy distribution on  Fedora 23 (and Scientific Linux 7) following the 'Installing with Anaconda Python instructions'. I followed the steps in 'Quickstart Guide' to use fermipy, but when I run 'gta.write_roi('fit_model')', I got an error : 'RuntimeError: In FT2Font: Can not load face'.

>>> gta.write_roi('fit_model')
2016-03-12 09:40:45 - GTBinnedAnalysis - INFO - Writing /home/k/p/fit_model_00.xml...
2016-03-12 09:40:45 - GTBinnedAnalysis - INFO - Generating model map for component 00.
2016-03-12 09:40:51 - GTAnalysis - INFO - Writing /home/k/p/fit_model.npy...
2016-03-12 09:40:51 - GTAnalysis - INFO - Writing /home/k/p/fit_model.yaml...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2545, in write_roi
    **kwargs.get('plotting',{}))
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2556, in make_plots
    plotter.run(self, mcube_maps, prefix=prefix, **kwargs)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/fermipy/plotting.py", line 684, in run
    format=format)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/fermipy/plotting.py", line 807, in make_roi_plots
    prefix, esuffix, format)))
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 688, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/figure.py", line 1565, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 196, in print_figure
    FigureCanvasAgg.print_figure(self, *args, **kwargs)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2232, in print_figure
    **kwargs)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 527, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 474, in draw
    self.figure.draw(self.renderer)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/figure.py", line 1159, in draw
    func(*args)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/wcsaxes/core.py", line 194, in draw
    super(WCSAxes, self).draw(renderer, inframe)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2324, in draw
    a.draw(renderer)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/text.py", line 749, in draw
    bbox, info, descent = textobj._get_layout(renderer)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/text.py", line 352, in _get_layout
    ismath=False)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 238, in get_text_width_height_descent
    font = self._get_agg_font(prop)
  File "/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 284, in _get_agg_font
    hinting_factor=rcParams['text.hinting_factor'])
RuntimeError: In FT2Font: Can not load face.

Thanks.

**Comment by woodmd** [comment] 2016-03-23 20:41
I'm not able to reproduce this error on SL7 but from the log it looks like there is a problem with the matplotlib installation.  One thing you could try would be to delete your ``.matplotlib`` directory.  Note that this will delete your matplotlibrc file so you may want to make a backup of this directory in case there are any parts of the configuration you want to restore later.

**Comment by jefemagril** [comment] 2016-04-11 17:10
Hello,

I'm getting the same error message on SL6. When I installed fermipy I allowed it to create a "miniconda" installation using condainstall.sh, so I think that should be a clean matplotlib install as well. As per the suggestion above, I tried renaming the $HOME/.matplotlib/ directory to ".matplotlib_bak/" and running again (i.e., restarting the python process and importing/instantiating again), but the error still occurs.

**Comment by kialio** [comment] 2016-04-11 17:14
Hi Jeff,

Can you point me to your setup and I can test this locally?

Jeremy

**Comment by kialio** [comment] 2016-04-12 15:53
Hi,

I've verified this in Jeff's install and I did it in a completely separate install and I see this error as well.  I'm not exactly sure what's going on at this point and will have to dig further.

I have a different install (STs from source and all of the python packages/fermipy installed from pip) and I don't see this error (there's a different, I think benign error that I'll report).

Jeremy

**Comment by kialio** [comment] 2016-04-12 18:39
Hi,

The following will diagnose the problem:

`> from matplotlib.font_manager import FontProperties, findfont
> prop = FontProperties()
> findfont(prop)
> u'<old science tools install>/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/Vera.ttf'`

so the cache still points to an incorrect font folder.  I'm not sure why.  If you then delete

`~/.cache/matplotlib`

the next time you run the above commands it'll rebuild the font cache:

`from fermipy.gtanalysis import GTAnalysis
~/miniconda2/envs/fermi-env/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')`

but I still get the same error in the end just with a different font:

`~/miniconda2/envs/fermi-env/lib/python2.7/site-packages/matplotlib/font_manager.py:1288: UserWarning: findfont: Font family [u'sans-serif'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
~/miniconda2/envs/fermi-env/lib/python2.7/site-packages/matplotlib/font_manager.py:1298: UserWarning: findfont: Could not match :family=Bitstream Vera Sans:style=normal:variant=normal:weight=400:stretch=normal:size=8.0. Returning ~/miniconda2/envs/fermi-env/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/Vera.ttf
  UserWarning)
`

I'm handing this off to Jeff for now.  I have some other things which are demanding my attention.

**Comment by ktzhao** [comment] 2016-04-13 00:44
Probably because before I install fermipy there are something  in my .bashrc file : 
“export HEADAS=/...
   . $HEADAS/headas-init.sh
    export FERMI_DIR=/...
    source $FERMI_DIR/fermi-init.sh" 

I reinstall sl7, and reinstall fermipy with Anaconda Python, only set the FERMI_DIR environment. 
It is work  well now.
Thank you!

**Comment by kialio** [comment] 2016-04-14 18:53
More debugging.  This works:

`import matplotlib.pyplot as plt
import numpy as np

img = np.random.rand(100,100)
p = plt.figure()
im = plt.imshow(img)
plt.savefig('test.png')`

But this throws the error:

`import pyLikelihood as pyLike

import matplotlib.pyplot as plt
import numpy as np

img = np.random.rand(100,100)
p = plt.figure()
im = plt.imshow(img)
plt.savefig('test.png')`

**Comment by kialio** [comment] 2016-04-14 20:36
But this works:

```
import matplotlib.pyplot as plt
import pyLikelihood as pyLike
import numpy as np
img = np.random.rand(100,100)
p = plt.figure()
im = plt.imshow(img)
plt.savefig('test.png')
```

A solution might be to import matplotlib early in gtanalysis.  THoughts?

**Comment by woodmd** [comment] 2016-04-14 21:00
I suspect the issue is that pyLikelihood is importing the ST matplotlib installation rather than the one in anaconda.  I can try playing with the ordering of the import statements to see if there is a way to ensure that matplotlib always gets imported before pyLikelihood.

**Comment by woodmd** [comment] 2016-04-14 23:36
I'm not able to reproduce this error on a clean install of SL6 or SL7 so it may be that an old matplotlib installation is leaving files behind somewhere.  Here's what I see when I run the same sequence to retrieve the font location:
```
In [1]: from matplotlib.font_manager import FontProperties, findfont
In [2]: prop = FontProperties()
In [3]: findfont(prop)
Out[3]: u'/home/vagrant/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/Vera.ttf'
```
Maybe you could try deleting and reinstalling matplotlib?  I think this command should do the trick:
```
conda install -f matplotlib
```

**Comment by kialio** [comment] 2016-04-15 17:02
I've tried uninstalling and reinstalling and making sure there aren't any conflicting libraries in the ST install.  I am not sure why this is happening on our SL6 system and not the VM.  I think the recommended solution for users with this error is to use the ST python and not Anaconda.  At least until we can figure out what's going on.

**Comment by jefemagril** [comment] 2016-04-20 17:35
Ok, well thanks to the focused investigation above by @kialio , it seems that adding an import for matplotlib before importing pyLikelihood actually does provide at least a temporary fix to this issue. I'm still not sure why this is, but the good thing is it works. I will start a pull request in a few minutes with the addition.

**Comment by woodmd** [comment] 2016-04-26 00:10
The current scheme for ordering imports is already pretty fragile so I would prefer to keep the matplotlib imports in the `plotting` module if possible.  For the moment I've reverted the temporary fix that Jeff implemented since it was breaking matplotlib on headless machines (like the travis CI builds).  Did you ever experiment with deleting both `.cache/matplotlib` and `.config/matplotlib`?  What do you see when you run the following:
```
>>> import matplotlib
>>> matplotlib.get_configdir()
```
It would be good if we could figure out how to reproduce this error starting from a clean install as that would make it much easier to debug.

**Comment by ktzhao** [comment] 2016-04-26 01:42
>>> import matplotlib
>>> matplotlib.get_configdir()
u'/home/k/.config/matplotlib'




(fermi-env)[k@kt ~]$ rm .cache/matplotlib/ -rf
(fermi-env)[k@kt ~]$ rm .config/matplotlib/ -rf
(fermi-env)[k@kt ~]$ python
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pyLikelihood as pyLike
>>> import matplotlib.pyplot as plt
/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
>>> import numpy as np
>>> img = np.random.rand(100,100)
>>> p = plt.figure()
>>> im = plt.imshow(img)
>>> plt.savefig('test.png')
/home/k/miniconda/envs/fermi-env/lib/python2.7/site-packages/matplotlib/font_manager.py:1288: UserWarning: findfont: Font family [u'sans-serif'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
...error...

**Comment by woodmd** [comment] 2016-05-03 23:26
Jeremy and I did some more digging on this and discovered that the font error only appears on ROOT builds.  For now I think we will just recommend that people only use non-ROOT builds.  @ktzhao before I close this issue could you confirm that switching to the non-ROOT build resolves the error for you?

**Comment by ktzhao** [comment] 2016-05-06 09:09
switching non-ROOT build resolved the problem. thank you! @woodmd

**Comment by woodmd** [comment] 2016-05-07 00:43
Great!  I'll make a note about using the non-ROOT builds in the installation instructions.

**Closed by woodmd** 2016-05-07 00:43 UTC
