### ISSUE TITLE
Light curve generation

### ISSUE THREAD

**Issue by vaidehiratna** [fermiPy/fermipy#114] opened 2017-01-19 02:17 UTC
I am trying to generate the light curve for the recent flare of CTA 102. I followed the input options given on fermiPy webpage but found that there are inputs, e.g., free_background, make_plots, are not accepted by the tool. It gives the following error

KeyError: 'Invalid configuration key: make_plots'

When I ran the tool without these options (but set free_radius=0), it generated folders and performed the fitting but ultimately got killed throwing a big chunk of error. Below I provide a section of the log
>>> lc = gta.lightcurve(srcname, free_radius=0)
2017-01-18 18:02:26 INFO    GTAnalysis.lightcurve(): Computing Lightcurve for 3FGL J2232.5+1143
2017-01-18 18:02:27 INFO    GTAnalysis._make_lc(): Fitting time range 503452804 503539204
2017-01-18 18:02:46 INFO    GTBinnedAnalysis.write_xml(): Writing /nfs/farm/g/glast/u/vaidehi/Individuals/CTA102/output/lightcurve_503452804_503539204/base_00.xml...
/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/scipy/interpolate/fitpack2.py:222: UserWarning: 
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  warnings.warn(message)
2017-01-18 18:02:48 INFO    GTBinnedAnalysis.write_xml(): Writing /nfs/farm/g/glast/u/vaidehi/Individuals/CTA102/output/lightcurve_503452804_503539204/fit_model_final_00.xml...
2017-01-18 18:02:48 INFO    GTAnalysis._make_lc(): Finished time range 503452804 503539204

................... lots of lines .......................

2017-01-18 18:08:14 INFO    GTAnalysis._make_lc(): Fitting time range 504748804 504835204
2017-01-18 18:08:35 INFO    GTBinnedAnalysis.write_xml(): Writing /nfs/farm/g/glast/u/vaidehi/Individuals/CTA102/output/lightcurve_504748804_504835204/base_00.xml...
   FUNCTION VALUE DOES NOT SEEM TO DEPEND ON ANY OF THE  1 VARIABLE PARAMETERS.
          VERIFY THAT STEP SIZES ARE BIG ENOUGH AND CHECK FCN LOGIC.
 *******************************************************************************
 *******************************************************************************

........... lots of lines similar to above ...........

2017-01-18 18:08:39 ERROR   GTAnalysis.fit(): MINUIT failed with status code 1 fit quality 1
2017-01-18 18:08:39 INFO    GTBinnedAnalysis.write_xml(): Writing /nfs/farm/g/glast/u/vaidehi/Individuals/CTA102/output/lightcurve_504748804_504835204/fit_model_final_00.xml...
/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/gtanalysis.py:2398: RuntimeWarning: divide by zero encountered in double_scalars
  val *= 1. / min(1.0, npred)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/lightcurve.py", line 85, in lightcurve
    o = self._make_lc(name, **config)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/lightcurve.py", line 236, in _make_lc
    output = gta.get_src_model(name)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/gtanalysis.py", line 3822, in get_src_model
    optimizer=optimizer)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/gtanalysis.py", line 2327, in profile_norm
    ul_confidence=0.99)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/utils.py", line 671, in get_parameter_limits
    sd = spline.derivative()
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/scipy/interpolate/fitpack2.py", line 456, in derivative
    tck = fitpack.splder(self._eval_args, n)
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/scipy/interpolate/fitpack.py", line 1221, in splder
    "and is not differentiable %d times") % n)
ValueError: The spline has internal repeated knots and is not differentiable 1 times

I am unable to understand the error. The source was in a extremely bright state (daily flux >5e-6 ph/cm2/s) but still it is failing to achieve convergence.

Please help.

Thanks.

**Comment by woodmd** [comment] 2017-01-19 02:47
The options you are trying to use were added in a newer release of fermipy than the one you're using.  The "latest" documentation page (http://fermipy.readthedocs.io/en/latest) corresponds to the documentation for the most recent commit to the master branch and may describe features that are not available in older releases.  You can find links to the documentation for older versions of fermipy in the "versions" tab that appears in the left sidebar when you click on the "Read The Docs" banner.

I don't know what's responsible for the other error you're seeing.  I'll have a look at it tomorrow to see if I can reproduce it.

I also noticed that you're using ST 11-05-00. I highly recommend that you switch to the latest ST release (11-05-01).  The release you're using had several serious bugs.

**Comment by woodmd** [comment] 2017-01-23 07:06
I investigated this issue further and it looks like this is a bug in the STs.  Namely for this time bin the predicted counts for all components that have energy dispersion enabled are exactly zero.  I was able to run the same analysis successfully with energy disabled (i.e. with `gtlike : {edisp : False} }`) so it appears there's some issue with how the energy dispersion correct is being applied.  I'll follow up with Eric to see if we can track down the source of this but in the meantime you can try running with energy dispersion disabled.  The dispersion correction is only ~3-4% so for a lightcurve the additional systematic incurred from disabling the correction is probably less than the statistical error anyway.

**Comment by vaidehiratna** [comment] 2017-01-23 18:54
I agree. When energy dispersion was switched off, the analysis completed without any issue. However, one interesting thing I noted is that the generated source_light_curve.fits file contains time and flux values but no spectral parameters (e.g., photon index, alpha, beta etc.).

**Comment by woodmd** [comment] 2017-01-24 17:14
I've committed some updates to master that add columns for spectral parameters to the output file.  These have the same names and format as the spectral parameter columns in the ROI file (`param_names`,`param_values`,`param_errors`).  I also fixed a few bugs in the logic for freeing/fixing sources.

**Closed** 2017-02-09 19:54 UTC
