### ISSUE TITLE
upgraded to 0.10.0 with FST v10r0p5 and gta.optimize() and gta.fit() now complain

### ISSUE THREAD

**Issue by jcisler** [fermiPy/fermipy#47] opened 2016-07-08 21:02 UTC
Hi there,

I upgraded my fermipy version to 0.10.0 today and now neither of the fitting or optimizing routines work. I get the following complaints. Your help would be greatly appreciated. (This is with me going back to the drawing board and following the PG1553 instructions online.)

>>> fit_results = gta.fit()
2016-07-08 15:54:03 INFO     GTAnalysis.fit(): Starting fit.
Generating SourceMap for 3FGL J1543.5+0451....................!
Generating SourceMap for 3FGL J1546.6+1812....................!
Generating SourceMap for 3FGL J1549.5+1709....................!
Generating SourceMap for 3FGL J1550.5+0526....................!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jcisler/Fermi_v10r0p5/ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin14.4.0-without-root/x86_64-apple-darwin14.4.0/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2909, in fit
    fit_output = self._fit(**config)
  File "/Users/jcisler/Fermi_v10r0p5/ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin14.4.0-without-root/x86_64-apple-darwin14.4.0/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2821, in _fit
    return self._fit_optimizer_iter(**kwargs)
  File "/Users/jcisler/Fermi_v10r0p5/ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin14.4.0-without-root/x86_64-apple-darwin14.4.0/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2716, in _fit_optimizer_iter
    quality, status, edm, loglike = self._fit_optimizer(**kwargs)
  File "/Users/jcisler/Fermi_v10r0p5/ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin14.4.0-without-root/x86_64-apple-darwin14.4.0/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2761, in _fit_optimizer
    'MINUIT'))
  File "/Users/jcisler/Fermi_v10r0p5/ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin14.4.0-without-root/x86_64-apple-darwin14.4.0/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2700, in _create_optObject
    optObject = optFactory.create(optimizer, self.like.logLike)
  File "/Users/jcisler/Fermi_v10r0p5/ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin14.4.0-without-root/x86_64-apple-darwin14.4.0/lib/python/pyLikelihood.py", line 2225, in create
    return lib_pyLikelihood.OptimizerFactory_create(*args)
TypeError: in method 'OptimizerFactory_create', argument 2 of type 'std::string const &'
>>>

**Comment by woodmd** [comment] 2016-07-08 21:47
I'm not able to reproduce this error when running the pg1553 notebook on my Yosemite machine with ST-10-00-05.  What are you doing to execute the notebook?  Did you download the fermipy-extra repository?

**Comment by jcisler** [comment] 2016-07-08 22:49
Here's the logfile (I've been running it, not from the notebook, but from the code I wrote based on the notebook):
--------------------------------------------------------------------------------
This is fermipy version 0.10.0.
2016-07-08 17:24:19 DEBUG    GTAnalysis.print_config(): Configuration:
binning:
  binsperdec: 8
  binsz: 0.1
  coordsys: CEL
  enumbins: null
  hpx_ebin: true
  hpx_order: 10
  hpx_ordering_scheme: RING
  npix: null
  proj: AIT
  projtype: WCS
  roiwidth: 10.0
components: []
data:
  cacheft1: true
  evfile: PG1553.lst
  ltcube: null
  scfile: L1511031432171D651E7F63_SC00.fits
extension:
  fix_background: false
  spatial_model: RadialGaussian
  sqrt_ts_threshold: null
  update: false
  width: null
  width_max: 1.0
  width_min: 0.01
  width_nstep: 21
fileio:
  logfile: /Users/jcisler/Fermi_Data/PG1553/pg1553/fermipy
  outdir: /Users/jcisler/Fermi_Data/PG1553/pg1553
  outdir_regex:
  - \.fits$|\.fit$|\.xml$|\.npy$|\.png$|\.pdf$|\.yaml$
  savefits: true
  scratchdir: /scratch
  usescratch: false
  workdir: null
  workdir_regex:
  - \.fits$|\.fit$|\.xml$|\.npy$
gtlike:
  bexpmap: null
  convolve: true
  edisp: true
  edisp_disable:
  - isodiff
  - galdiff
  irfs: P8R2_SOURCE_V6
  llscan_npts: 20
  minbinsz: 0.05
  resample: true
  rfactor: 2
  srcmap: null
localize:
  dtheta_max: 0.3
  fix_background: true
  nstep: 5
  update: false
logging:
  chatter: 3
  verbosity: 3
mc:
  seed: null
model:
  assoc_xmatch_columns:
  - 3FGL_Name
  catalogs:
  - 3FGL
  diffuse: []
  extdir: null
  extract_diffuse: false
  galdiff:
  - $FERMI_DIFFUSE_DIR/gll_iem_v06.fits
  isodiff:
  - $FERMI_DIFFUSE_DIR/iso_P8R2_SOURCE_V6_v06.txt
  limbdiff: []
  merge_sources: true
  sources: []
  src_radius: null
  src_radius_roi: null
  src_roiwidth: 15.0
optimizer:
  init_lambda: 0.0001
  max_iter: 100
  min_fit_quality: 2
  optimizer: NEWMINUIT
  retries: 3
  tol: 0.001
  verbosity: 0
plotting:
  catalogs: []
  cmap: ds9_b
  format: png
  graticule_radii: []
  label_ts_threshold: 0.0
  loge_bounds: []
residmap:
  loge_bounds: []
  model: {}
roiopt:
  max_free_sources: 5
  npred_frac: 0.95
  npred_threshold: 1.0
  shape_ts_threshold: 25.0
  skip: []
sed:
  bin_index: 2.0
  cov_scale: 3.0
  fix_background: true
  ul_confidence: 0.95
  use_local_index: false
selection:
  convtype: null
  dec: null
  emax: 300000.0
  emin: 100.0
  evclass: 128
  evtype: 3
  filter: DATA_QUAL>0 && LAT_CONFIG==1
  glat: null
  glon: null
  logemax: null
  logemin: null
  ra: null
  radius: null
  roicut: 'yes'
  target: 3FGL J1555.7+1111
  tmax: null
  tmin: null
  zmax: 90.0
sourcefind:
  max_iter: 3
  min_separation: 1.0
  model: {}
  sources_per_iter: 3
  sqrt_ts_threshold: 3.0
  tsmap_fitter: tsmap
tscube:
  cov_scale: -1.0
  cov_scale_bb: -1.0
  do_sed: true
  init_lambda: 0
  max_iter: 30
  model: {}
  nnorm: 10
  norm_sigma: 5.0
  remake_test_source: false
  st_scan_level: 0
  tol: 0.001
  tol_type: 0
tsmap:
  loge_bounds: []
  max_kernel_radius: 3.0
  model: {}
  multithread: false

2016-07-08 17:24:19 DEBUG    ROIModel.load(): Starting
2016-07-08 17:24:19 DEBUG    ROIModel.load_fits_catalog(): Loading FITS catalog: 3FGL
2016-07-08 17:24:25 DEBUG    ROIModel.load(): Starting
2016-07-08 17:24:25 DEBUG    ROIModel.load_fits_catalog(): Loading FITS catalog: 3FGL
2016-07-08 17:24:26 DEBUG    GTAnalysis._create_component(): Creating Analysis Component: 00
2016-07-08 17:24:26 DEBUG    ROIModel.load(): Starting
2016-07-08 17:24:26 DEBUG    ROIModel.load_fits_catalog(): Loading FITS catalog: 3FGL
2016-07-08 17:24:32 DEBUG    ROIModel.load(): Starting
2016-07-08 17:24:32 DEBUG    ROIModel.load_fits_catalog(): Loading FITS catalog: 3FGL
2016-07-08 17:24:32 DEBUG    GTBinnedAnalysis.__init__(): Automatically setting selection radius to 7.57106781187 deg
2016-07-08 17:24:32 DEBUG    GTBinnedAnalysis.print_config(): Configuration:
binning:
  binsperdec: 8
  binsz: 0.1
  coordsys: CEL
  enumbins: null
  hpx_ebin: true
  hpx_order: 10
  hpx_ordering_scheme: RING
  npix: null
  proj: AIT
  projtype: WCS
  roiwidth: 10.0
data:
  cacheft1: true
  evfile: PG1553.lst
  ltcube: null
  scfile: L1511031432171D651E7F63_SC00.fits
file_suffix: _00
fileio:
  logfile: /Users/jcisler/Fermi_Data/PG1553/pg1553/fermipy
  outdir: /Users/jcisler/Fermi_Data/PG1553/pg1553
  outdir_regex:
  - \.fits$|\.fit$|\.xml$|\.npy$|\.png$|\.pdf$|\.yaml$
  savefits: true
  scratchdir: /scratch
  usescratch: false
  workdir: /Users/jcisler/Fermi_Data/PG1553/pg1553
  workdir_regex:
  - \.fits$|\.fit$|\.xml$|\.npy$
gtlike:
  bexpmap: null
  convolve: true
  edisp: true
  edisp_disable:
  - isodiff
  - galdiff
  irfs: P8R2_SOURCE_V6
  llscan_npts: 20
  minbinsz: 0.05
  resample: true
  rfactor: 2
  srcmap: null
logging:
  chatter: 3
  verbosity: 3
model:
  assoc_xmatch_columns:
  - 3FGL_Name
  catalogs:
  - 3FGL
  diffuse: []
  extdir: null
  extract_diffuse: false
  galdiff:
  - $FERMI_DIFFUSE_DIR/gll_iem_v06.fits
  isodiff:
  - $FERMI_DIFFUSE_DIR/iso_P8R2_SOURCE_V6_v06.txt
  limbdiff: []
  merge_sources: true
  sources: []
  src_radius: null
  src_radius_roi: null
  src_roiwidth: 15.0
name: '00'
selection:
  convtype: null
  dec: null
  emax: 300000.0
  emin: 100.0
  evclass: 128
  evtype: 3
  filter: DATA_QUAL>0 && LAT_CONFIG==1
  glat: null
  glon: null
  logemax: null
  logemin: null
  ra: null
  radius: 7.5710678118654755
  roicut: 'yes'
  target: 3FGL J1555.7+1111
  tmax: null
  tmin: null
  zmax: 90.0

2016-07-08 17:24:33 INFO     GTAnalysis.setup(): Running setup
2016-07-08 17:24:33 INFO     GTBinnedAnalysis.setup(): Running setup for Analysis Component: 00
2016-07-08 17:24:33 DEBUG    GTBinnedAnalysis.setup(): Skipping gtltcube
2016-07-08 17:24:33 DEBUG    GTBinnedAnalysis.setup(): Loading LT Cube /Users/jcisler/Fermi_Data/PG1553/pg1553/ltcube_00.fits
2016-07-08 17:24:33 DEBUG    GTBinnedAnalysis.setup(): Creating PSF model
2016-07-08 17:24:35 DEBUG    GTBinnedAnalysis.setup(): Skipping gtbin
2016-07-08 17:24:35 DEBUG    GTBinnedAnalysis.setup(): Skipping gtexpcube
2016-07-08 17:24:35 DEBUG    GTBinnedAnalysis.setup(): Skipping local gtexpcube
2016-07-08 17:24:35 DEBUG    GTBinnedAnalysis.setup(): Skipping gtsrcmaps
2016-07-08 17:24:35 DEBUG    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedObs
2016-07-08 17:24:35 DEBUG    GTBinnedAnalysis._create_binned_analysis(): {'irfs': 'P8R2_SOURCE_V6', 'expCube': u'/Users/jcisler/Fermi_Data/PG1553/pg1553/ltcube_00.fits', 'srcMaps': u'/Users/jcisler/Fermi_Data/PG1553/pg1553/srcmap_00.fits', 'binnedExpMap': u'/Users/jcisler/Fermi_Data/PG1553/pg1553/bexpmap_00.fits'}
2016-07-08 17:24:36 DEBUG    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis
2016-07-08 17:24:36 DEBUG    GTBinnedAnalysis._create_binned_analysis(): {'minbinsz': 0.05, 'convolve': True, 'optimizer': u'MINUIT', 'resamp_fact': 2, 'srcModel': u'/Users/jcisler/Fermi_Data/PG1553/pg1553/srcmdl_00.xml', 'resample': True}
2016-07-08 17:24:40 DEBUG    GTBinnedAnalysis._create_binned_analysis(): Enabling energy dispersion
2016-07-08 17:24:40 DEBUG    GTBinnedAnalysis._create_binned_analysis(): Disabling energy dispersion for isodiff
2016-07-08 17:24:40 DEBUG    GTBinnedAnalysis._create_binned_analysis(): Disabling energy dispersion for galdiff
2016-07-08 17:24:40 DEBUG    GTBinnedAnalysis._create_binned_analysis(): Computing fixed weights
2016-07-08 17:24:49 DEBUG    GTBinnedAnalysis._create_binned_analysis(): Updating source maps
2016-07-08 17:24:49 INFO     GTBinnedAnalysis.setup(): Finished setup for Analysis Component: 00
2016-07-08 17:24:49 INFO     GTAnalysis.setup(): Initializing source properties
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1540.8+1449
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1540.8+1449
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1541.6+1414
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1541.6+1414
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1541.8+1105
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1541.8+1105
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1543.5+0451
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1543.5+0451
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1546.0+0818
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1546.0+0818
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1546.6+1812
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1546.6+1812
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1548.4+1455
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1548.4+1455
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1549.5+1709
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1549.5+1709
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1550.5+0526
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1550.5+0526
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1552.1+0852
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1552.1+0852
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1553.5+1256
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1553.5+1256
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1555.7+1111
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1555.7+1111
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1603.7+1106
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1603.7+1106
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1607.0+1551
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1607.0+1551
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1608.6+1029
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1608.6+1029
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source 3FGL J1611.9+1404
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for 3FGL J1611.9+1404
2016-07-08 17:24:49 DEBUG    GTAnalysis.setup(): Initializing source galdiff
2016-07-08 17:24:49 DEBUG    GTAnalysis.get_src_model(): Generating source dict for galdiff
2016-07-08 17:24:58 DEBUG    GTAnalysis.setup(): Initializing source isodiff
2016-07-08 17:24:58 DEBUG    GTAnalysis.get_src_model(): Generating source dict for isodiff
2016-07-08 17:24:58 INFO     GTAnalysis.setup(): Finished setup
2016-07-08 17:24:58 INFO     GTAnalysis.optimize(): Starting
2016-07-08 17:24:58 DEBUG    GTAnalysis.optimize(): LogLike: -50500.265839
2016-07-08 17:24:58 DEBUG    GTAnalysis.free_source(): Freeing parameters for galdiff               : ['Prefactor']
2016-07-08 17:24:58 DEBUG    GTAnalysis.free_source(): Freeing parameters for isodiff               : ['Normalization']
2016-07-08 17:24:58 DEBUG    GTAnalysis.free_source(): Freeing parameters for 3FGL J1555.7+1111     : ['norm']
2016-07-08 17:24:58 DEBUG    GTAnalysis.free_source(): Freeing parameters for 3FGL J1553.5+1256     : ['norm']
2016-07-08 17:24:58 DEBUG    GTAnalysis.free_source(): Freeing parameters for 3FGL J1608.6+1029     : ['Prefactor']
2016-07-08 17:24:58 DEBUG    GTAnalysis.fit(): Starting fit.
2016-07-08 17:25:02 DEBUG    GTAnalysis._fit_optimizer_iter(): Fit iteration: 0

**Comment by woodmd** [comment] 2016-07-08 23:46
I identified the source of the problem -- there was a typo in the if statement checking for the NEWMINUIT optimizer.  I will plan to make a patch release that fixes this issue but in the meantime you should be able to work around it by using the MINUIT optimizer.

**Comment by woodmd** [comment] 2016-07-10 22:33
This issue should now be fixed in 0.10.1 release.

**Closed by woodmd** 2016-07-10 22:33 UTC

**Comment by jcisler** [comment] 2016-07-11 19:42
Great, thanks so much!

I ran it with Minuit and it worked perfectly.
